import { useBlockProps, InnerBlocks } from '@wordpress/block-editor';

export default function Save() {
    const blockProps = useBlockProps.save();

    return (
        <div {...blockProps}>
            <div className="wp-timeline-container">
                <div className="wp-timeline-years">
                    {/* Years will be dynamically generated by JavaScript */}
                </div>
                <div className="wp-timeline-content">
                    <InnerBlocks.Content />
                </div>
            </div>
        </div>
    );
}